sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t systtek/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true systtek/docker-react npm run test