sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t systtek/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true systtek/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-865635137469"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY